### ISSUE TITLE
`headless` is not included in published package

### ISSUE THREAD

**Issue by fanatid** [substack/browser-launcher#50]
`headless` in `bundleDependencies`, but published package do not have code for this package, so `3.0.0` is broken. Republish please...

**Comment by bcomnes** [comment]
can you send a pr?

**Comment by bcomnes** [comment]
OH right removed the checked in node_modules path. I guess I forgot to remove this.  Its safe to just remove this field right?

**Comment by fanatid** [comment]
PR: #53 
I think it should be safe to remove `bundleDependencies` field. Do you know why this used initially?

**Comment by bcomnes** [comment]
There was a patch applied to a dependency in node_modules, and committed to the code base.  I think its just an artifact of that process since that was removed.
